CC = gcc

all: 1 2 3 4 5 6 7 8

1: 1.o
	$(CC) 1.o -o 1

1.o: 1.c
	$(CC) -c 1.c -o 1.o

2: 2.o
	$(CC) 2.o -o 2

2.o: 2.c
	$(CC) -c 2.c -o 2.o

3: 3.o
	$(CC) 3.o -o 3

3.o: 3.c
	$(CC) -c 3.c -o 3.o

4: 4.o
	$(CC) 4.o -o 4

4.o: 4.c
	$(CC) -c 4.c -o 4.o

5: 5.o
	$(CC) 5.o -o 5

5.o: 5.c
	$(CC) -c 5.c -o 5.o

6: 6.o
	$(CC) 6.o -o 6

6.o: 6.c
	$(CC) -c 6.c -o 6.o

7: 7.o
	$(CC) 7.o -o 7

7.o: 7.c
	$(CC) -c 7.c -o 7.o

8: 8.o
	$(CC) 8.o -o 8

8.o: 8.c
	$(CC) -c 8.c -o 8.o

clean:
	rm -rf 1.o 1 2.o 2 2.output 3.o 3 4.o 4 5.o 5 6.o 6 7.o 7 8.o 8